services:
  mario-v5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Mario-Leaderboard
    ports:
      - "18673:80"
    volumes:
      - mario-scores:/data
    restart: unless-stopped

volumes:
  mario-scores:
